spring.application.name=Server
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=JDBC:mysql://mysql-myproject-tranbichngoc855-32f5.l.aivencloud.com:13500/defaultdb?useSSL=true&trustServerCertificate=true
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_eJqlBg8KyyRVWk4V_zv
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect