spring.application.name=Server
spring.jpa.hibernate.ddl-auto=create
spring.datasource.url=JDBC:mysql://${MYSQL_HOST:localhost}:3306/systemdb
spring.datasource.username=root
spring.datasource.password=${MYSQL_PASSWORD:123456}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect